name: gh-pages-Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Build React Static Files
        run: npm run build

      # Github Pages Action Documentation - by peaceiris
      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # For use in deploying to another repository
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # external_repository: braingeneers/react-demo
          # publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
